<script setup lang="ts">
import { onMounted, reactive, ref } from 'vue'
import { ElMessage, ElMessageBox } from 'element-plus'
import { organizationApi } from '@/api/modules/organization'

const companies = ref<Record<string, unknown>[]>([]); const departments = ref<Record<string, unknown>[]>([]); const company = ref(''); const companyDialog = reactive({ open: false, name: '', parentCompanyName: '', level: 1 }); const departmentDialog = reactive({ open: false, name: '', parentDepartmentName: '', companyName: '', leaderName: '' })
function idOf(value: Record<string, unknown>) { return Number(value.id) }
function nameOf(value: Record<string, unknown>) { return String(value.name ?? '') }
async function loadCompanies() { try { companies.value = await organizationApi.companies(); if (!company.value && companies.value.length) company.value = nameOf(companies.value[0]!); if (company.value) departments.value = await organizationApi.departments(company.value) } catch (error) { ElMessage.error(error instanceof Error ? error.message : '组织数据加载失败') } }
async function selectCompany() { departments.value = await organizationApi.departments(company.value) }
async function addCompany() { try { await organizationApi.addCompany(companyDialog); companyDialog.open = false; await loadCompanies(); ElMessage.success('公司已新增') } catch (error) { ElMessage.error(error instanceof Error ? error.message : '新增失败') } }
async function removeCompany(item: Record<string, unknown>) { try { await ElMessageBox.confirm(`确定删除公司“${nameOf(item)}”吗？`, '请确认', { type: 'warning' }); await organizationApi.deleteCompany(idOf(item)); await loadCompanies() } catch (error) { if (error instanceof Error) ElMessage.error(error.message) } }
function openDepartment() { Object.assign(departmentDialog, { open: true, name: '', parentDepartmentName: '', companyName: company.value, leaderName: '' }) }
async function addDepartment() { try { await organizationApi.addDepartment(departmentDialog); departmentDialog.open = false; await selectCompany(); ElMessage.success('部门已新增') } catch (error) { ElMessage.error(error instanceof Error ? error.message : '新增失败') } }
async function removeDepartment(item: Record<string, unknown>) { try { await ElMessageBox.confirm(`确定删除部门“${nameOf(item)}”吗？`, '请确认', { type: 'warning' }); await organizationApi.deleteDepartment(idOf(item)); await selectCompany() } catch (error) { if (error instanceof Error) ElMessage.error(error.message) } }
onMounted(loadCompanies)
</script>

<template><div class="page"><div class="page-header"><div><h1 class="page-title">组织管理</h1><p class="page-description">管理员次优先功能，不作为本期验收门槛</p></div></div><div class="admin-grid"><section class="surface"><div class="toolbar"><h2>公司</h2><el-button type="primary" @click="companyDialog.open=true">新增</el-button></div><div class="item-list"><button v-for="item in companies" :key="idOf(item)" :class="['item', { active: company === nameOf(item) }]" @click="company=nameOf(item); selectCompany()"><span>{{ nameOf(item) }}</span><el-button link type="danger" @click.stop="removeCompany(item)">删除</el-button></button></div></section><section class="surface"><div class="toolbar"><h2>{{ company || '公司' }} · 部门</h2><el-button type="primary" :disabled="!company" @click="openDepartment">新增部门</el-button></div><el-table :data="departments" style="margin-top:14px"><el-table-column prop="name" label="部门" /><el-table-column prop="code" label="编码" /><el-table-column prop="leaderName" label="负责人" /><el-table-column label="操作" width="80"><template #default="{ row }"><el-button link type="danger" @click="removeDepartment(row)">删除</el-button></template></el-table-column></el-table></section></div><el-dialog v-model="companyDialog.open" title="新增公司" width="460px"><el-form label-position="top"><el-form-item label="公司名称"><el-input v-model="companyDialog.name" /></el-form-item><el-form-item label="上级公司"><el-input v-model="companyDialog.parentCompanyName" /></el-form-item><el-form-item label="层级"><el-input-number v-model="companyDialog.level" :min="1" /></el-form-item></el-form><template #footer><el-button @click="companyDialog.open=false">取消</el-button><el-button type="primary" @click="addCompany">保存</el-button></template></el-dialog><el-dialog v-model="departmentDialog.open" title="新增部门" width="460px"><el-form label-position="top"><el-form-item label="部门名称"><el-input v-model="departmentDialog.name" /></el-form-item><el-form-item label="上级部门"><el-input v-model="departmentDialog.parentDepartmentName" /></el-form-item><el-form-item label="负责人"><el-input v-model="departmentDialog.leaderName" /></el-form-item></el-form><template #footer><el-button @click="departmentDialog.open=false">取消</el-button><el-button type="primary" @click="addDepartment">保存</el-button></template></el-dialog></div></template>

<style scoped>.admin-grid { display:grid; grid-template-columns:340px minmax(0,1fr); gap:16px; }.surface h2 { margin:0; font-size:17px; }.item-list { display:flex; flex-direction:column; gap:6px; margin-top:16px; }.item { display:flex; align-items:center; justify-content:space-between; padding:10px 12px; color:inherit; cursor:pointer; background:transparent; border:0; border-radius:8px; }.item:hover,.item.active { background:var(--wo-primary-soft); }.item.active { color:var(--wo-primary); font-weight:650; }</style>
